---
bench_home_vg: vg0
bench_home_size: 128G

bench_enable_tuned_cpu_partitioning: true
isolated_cores: "0-11"

bench_enable_web_export: true

# yamllint disable rule:line-length
host_description: >-
  [aoc-rs](https://github.com/ictrobot/aoc-rs) benchmarks running on a
  [Hetzner EX44](https://www.hetzner.com/dedicated-rootserver/ex44/) server with an
  [Intel i5-13500](https://www.intel.com/content/www/us/en/products/sku/230580/intel-core-i513500-processor-24m-cache-up-to-4-80-ghz/specifications.html).
  Benchmarks are isolated to the 6 P-cores.
# yamllint enable rule:line-length
