#!/usr/bin/env python3
"""Prune the year crates in a checkout down to a single day number.

Rewrites each crates/yearYYYY/src/lib.rs so the utils::year! list keeps only the given day, any days it references,
and any shared modules the kept files reference. Years without the provided day keep their lowest day instead, so every
year crate still compiles.

Only the exact source forms xtask generates are understood, and anything else is an error.

The script errors on code not matching the expected format, ensuring pruning is successful or the build fails.
Entries and mod declarations must also match the day and module files exactly, or an error is raised.

The committed file contents are read from git, so pruning for one day after another needs no restore step in
between. The worktree file is only written when the output actually differs, which keeps cargo from recompiling
crates whose pruned contents are the same as the previous day's.

Usage: prune.py <checkout> <day-number>
"""
import re
import subprocess
import sys
from pathlib import Path

# The exact forms generated by xtask, verified against every commit.
YEAR_START = re.compile(r"^utils::year!\(\d{4} => year\d{4}, \$\{$")
YEAR_END = re.compile(r"^\}\);$")
YEAR_ENTRY = re.compile(r"^    (\d+) => day(\d{2})::Day\d{2}(?:<'_>)?,$")
MOD_LINE = re.compile(r"^mod (\w+);$")
USE_CRATE = re.compile(r"^\s*use crate::(\w+)[\w:{}, ]*;$")
INLINE_CRATE = re.compile(r"\bcrate::(\w+)")
LINE_COMMENT = re.compile(r"//[^\n]*")
DAY_NAME = re.compile(r"day\d{2}")


def committed(checkout: Path, rel: str) -> str:
    """The checked out commit's version of a file, which is the clean source regardless of any earlier lib pruning."""
    r = subprocess.run(["git", "-C", str(checkout), "show", f"HEAD:{rel}"], capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"git show HEAD:{rel}: {r.stderr.strip()[:200]}")
    return r.stdout


def write_if_changed(path: Path, content: str) -> None:
    """Write only when the content differs, so cargo's fingerprints stay unchanged for unchanged crates."""
    if not path.exists() or path.read_text() != content:
        path.write_text(content)


def day_name(name: str) -> str:
    """DayNN and dayNN both refer to the day's module."""
    return f"day{name[3:]}" if re.fullmatch(r"Day\d{2}", name) else name


def file_deps(path: Path) -> set:
    """The module and day names a source file references.

    Dependencies appear as `use crate::module::...;` statements or inline crate:: paths. A use of crate:: in any
    other form is an error."""
    deps = set()
    for line in LINE_COMMENT.sub("", path.read_text()).splitlines():
        if re.match(r"\s*use\b", line) and "crate::" in line:
            m = USE_CRATE.match(line)
            if not m or line.count("crate::") != 1:
                raise RuntimeError(f"{path}: unrecognised use of crate:: ({line.strip()!r}), refusing to prune")
            deps.add(day_name(m.group(1)))
            continue
        for m in INLINE_CRATE.finditer(line):
            deps.add(day_name(m.group(1)))
    return deps


def module_deps(srcdir: Path, name: str) -> set:
    """The names referenced by a module, which is either a name.rs file or a name/ directory of files."""
    deps = set()
    file = srcdir / f"{name}.rs"
    if file.exists():
        deps |= file_deps(file)
    directory = srcdir / name
    if directory.is_dir():
        for file in sorted(directory.rglob("*.rs")):
            deps |= file_deps(file)
    return deps


def parse_lib(lib: Path, text: str):
    """The entry and mod declaration line numbers of a year crate's lib.rs.

    The year! block must appear exactly once and contain only entry lines. Line comments are stripped before
    matching, and lines that are only a comment are ignored and kept as they are."""
    entries = {}
    mods = {}
    start = end = None
    for i, raw in enumerate(text.splitlines()):
        line = LINE_COMMENT.sub("", raw).rstrip()
        if YEAR_START.match(line):
            if start is not None:
                raise RuntimeError(f"{lib}:{i + 1}: second utils::year! block")
            start = i
            continue
        if start is not None and end is None:
            if not line.strip():
                continue
            if YEAR_END.match(line):
                end = i
                continue
            m = YEAR_ENTRY.match(line)
            if not m:
                raise RuntimeError(f"{lib}:{i + 1}: unrecognised line in the utils::year! block ({line.strip()!r})")
            day = int(m.group(1))
            if day != int(m.group(2)) or day in entries:
                raise RuntimeError(f"{lib}:{i + 1}: bad or duplicate entry")
            entries[day] = i
            continue
        if line.startswith("mod "):
            m = MOD_LINE.match(line)
            if not m:
                raise RuntimeError(f"{lib}:{i + 1}: unrecognised mod declaration ({line.strip()!r})")
            if m.group(1) in mods:
                raise RuntimeError(f"{lib}:{i + 1}: duplicate mod {m.group(1)}")
            mods[m.group(1)] = i
    if start is None or end is None:
        raise RuntimeError(f"{lib}: utils::year! block missing or unterminated")
    return entries, mods


def prune_year(checkout: Path, srcdir: Path, day: int) -> None:
    """Rewrite one year crate's lib.rs down to the given day number."""
    lib = srcdir / "lib.rs"
    text = committed(checkout, str(lib.relative_to(checkout)))
    entries, mods = parse_lib(lib, text)

    # Entries and declarations must match the files exactly, in both directions, to validate parsing was correct.
    day_files = {int(f.name[3:5]) for f in srcdir.glob("day[0-9][0-9].rs")}
    mismatch = day_files ^ set(entries)
    if mismatch:
        raise RuntimeError(f"{lib}: days {sorted(mismatch)} missing an entry or a file, refusing to prune")
    module_files = {p.stem for p in srcdir.glob("*.rs") if p.name != "lib.rs" and not DAY_NAME.fullmatch(p.stem)}
    module_files |= {p.name for p in srcdir.iterdir() if p.is_dir()}
    mismatch = module_files ^ set(mods)
    if mismatch:
        raise RuntimeError(f"{lib}: modules {sorted(mismatch)} missing a declaration or a file, refusing to prune")

    if day not in entries:
        # Canonical minimal content for years which don't have the requested day.
        day = min(entries)

    # Keep the day plus everything it references, transitively.
    known = {f"day{d:02d}" for d in entries} | set(mods)
    keep = {f"day{day:02d}"}
    frontier = set(keep)
    while frontier:
        refs = set()
        for name in frontier:
            if DAY_NAME.fullmatch(name):
                refs |= file_deps(srcdir / f"{name}.rs")
            else:
                refs |= module_deps(srcdir, name)
        unknown = refs - known
        if unknown:
            raise RuntimeError(f"{lib}: crate:: references to unknown {sorted(unknown)}, refusing to prune")
        frontier = refs - keep
        keep |= refs

    # Drop the entries and mod declarations which are not kept.
    lines = text.splitlines(keepends=True)
    drop = {i for d, i in entries.items() if f"day{d:02d}" not in keep}
    drop |= {i for m, i in mods.items() if m not in keep}

    # Collapse the blank runs left by dropped lines, as the lib.rs line numbers appear in the binaries through panic
    # locations in the macro expansions.
    out = []
    prev_blank = False
    for i, line in enumerate(lines):
        if i in drop:
            continue
        blank = line.strip() == ""
        if not (blank and prev_blank):
            out.append(line)
        prev_blank = blank
    write_if_changed(lib, "".join(out))


def main():
    checkout, day = Path(sys.argv[1]), int(sys.argv[2])
    for ydir in sorted(checkout.glob("crates/year*/src")):
        prune_year(checkout, ydir, day)


if __name__ == "__main__":
    main()
